#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RollifyAndroid.Resource", IsApplication=true)]

namespace RollifyAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f070000
			public const int formulaListItemMenu = 2131165184;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int calculatorButton = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int calculatorButtonPressed = 2130968577;
			
			// aapt resource value: 0x7f040006
			public const int emphasizedButton = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int emphasizedButtonPressed = 2130968583;
			
			// aapt resource value: 0x7f040002
			public const int operatorButton = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int operatorButtonPressed = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int toolbarButton = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int toolbarButtonPressed = 2130968581;
			
			// aapt resource value: 0x7f040008
			public const int uiControlButton = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int uiControlButtonPressed = 2130968585;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050003
			public const int calculatorButtonElevation = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int calculatorOperatorTextSize = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int calculatorSpaceSize = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int calculatorTextSize = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int slidingDrawerElevation = 2131034116;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int calc_toolbar_button = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_backspace_white_24dp = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int operator_button = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09001d
			public const int addFormulaButton = 2131296285;
			
			// aapt resource value: 0x7f090021
			public const int backspaceImageButton = 2131296289;
			
			// aapt resource value: 0x7f090023
			public const int button1 = 2131296291;
			
			// aapt resource value: 0x7f09002b
			public const int calcAdd = 2131296299;
			
			// aapt resource value: 0x7f090031
			public const int calcDiv = 2131296305;
			
			// aapt resource value: 0x7f09002f
			public const int calcMul = 2131296303;
			
			// aapt resource value: 0x7f09002d
			public const int calcSub = 2131296301;
			
			// aapt resource value: 0x7f09000b
			public const int calc_0 = 2131296267;
			
			// aapt resource value: 0x7f090008
			public const int calc_1 = 2131296264;
			
			// aapt resource value: 0x7f090009
			public const int calc_2 = 2131296265;
			
			// aapt resource value: 0x7f09000a
			public const int calc_3 = 2131296266;
			
			// aapt resource value: 0x7f090005
			public const int calc_4 = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int calc_5 = 2131296262;
			
			// aapt resource value: 0x7f090007
			public const int calc_6 = 2131296263;
			
			// aapt resource value: 0x7f090002
			public const int calc_7 = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int calc_8 = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int calc_9 = 2131296260;
			
			// aapt resource value: 0x7f09000d
			public const int calc_close_paren = 2131296269;
			
			// aapt resource value: 0x7f09000c
			public const int calc_open_paren = 2131296268;
			
			// aapt resource value: 0x7f090012
			public const int cancelButton = 2131296274;
			
			// aapt resource value: 0x7f090036
			public const int content = 2131296310;
			
			// aapt resource value: 0x7f09003a
			public const int debugTextView = 2131296314;
			
			// aapt resource value: 0x7f090010
			public const int formulaExpression = 2131296272;
			
			// aapt resource value: 0x7f090039
			public const int formulaListContainer = 2131296313;
			
			// aapt resource value: 0x7f090014
			public const int formulaListView = 2131296276;
			
			// aapt resource value: 0x7f09000f
			public const int formulaName = 2131296271;
			
			// aapt resource value: 0x7f090001
			public const int gridLayout1 = 2131296257;
			
			// aapt resource value: 0x7f090037
			public const int handle = 2131296311;
			
			// aapt resource value: 0x7f090024
			public const int imageButton1 = 2131296292;
			
			// aapt resource value: 0x7f090011
			public const int linearLayout1 = 2131296273;
			
			// aapt resource value: 0x7f09002a
			public const int linearLayout3 = 2131296298;
			
			// aapt resource value: 0x7f090026
			public const int linearLayout4 = 2131296294;
			
			// aapt resource value: 0x7f090016
			public const int linearLayout5 = 2131296278;
			
			// aapt resource value: 0x7f090019
			public const int linearLayout7 = 2131296281;
			
			// aapt resource value: 0x7f090015
			public const int linearLayout8 = 2131296277;
			
			// aapt resource value: 0x7f090028
			public const int numpadContainer = 2131296296;
			
			// aapt resource value: 0x7f090000
			public const int relativeLayout1 = 2131296256;
			
			// aapt resource value: 0x7f090033
			public const int rollButton = 2131296307;
			
			// aapt resource value: 0x7f090017
			public const int rollFormulaEditText = 2131296279;
			
			// aapt resource value: 0x7f090018
			public const int rollResult = 2131296280;
			
			// aapt resource value: 0x7f090013
			public const int saveButton = 2131296275;
			
			// aapt resource value: 0x7f090038
			public const int slidingDrawer1 = 2131296312;
			
			// aapt resource value: 0x7f09001a
			public const int space1 = 2131296282;
			
			// aapt resource value: 0x7f09002c
			public const int space10 = 2131296300;
			
			// aapt resource value: 0x7f09002e
			public const int space11 = 2131296302;
			
			// aapt resource value: 0x7f090030
			public const int space12 = 2131296304;
			
			// aapt resource value: 0x7f090032
			public const int space13 = 2131296306;
			
			// aapt resource value: 0x7f090034
			public const int space14 = 2131296308;
			
			// aapt resource value: 0x7f090035
			public const int space15 = 2131296309;
			
			// aapt resource value: 0x7f090029
			public const int space16 = 2131296297;
			
			// aapt resource value: 0x7f09001c
			public const int space2 = 2131296284;
			
			// aapt resource value: 0x7f09001e
			public const int space3 = 2131296286;
			
			// aapt resource value: 0x7f09001f
			public const int space4 = 2131296287;
			
			// aapt resource value: 0x7f090020
			public const int space5 = 2131296288;
			
			// aapt resource value: 0x7f090022
			public const int space6 = 2131296290;
			
			// aapt resource value: 0x7f090025
			public const int space7 = 2131296293;
			
			// aapt resource value: 0x7f090027
			public const int space8 = 2131296295;
			
			// aapt resource value: 0x7f09001b
			public const int swapCalcModeButton = 2131296283;
			
			// aapt resource value: 0x7f09000e
			public const int textView1 = 2131296270;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CalcNumpad = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int FormulaDetails = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int FormulaList = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060004
			public const int addFormulaButton = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int app_name = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int formulaNameTextField = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int rollButton = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int rollResult = 2131099649;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080001
			public const int BigTextButton = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int BigTextButton_Vertical = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int BigTextButton_VerticalDouble = 2131230723;
			
			// aapt resource value: 0x7f080000
			public const int CalcTextButton = 2131230720;
			
			// aapt resource value: 0x7f080004
			public const int CalcTextButton_Horizontal = 2131230724;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
